---
title: "Create a receptor file for AERMOD"
author: "MPCA - Risk evaluation and air modeling, EAO"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Method for updating AERMOD dispersion factors}
---


## Mission
Create a receptor file for AERMOD with rings of receptors at specified distances from an emissions source.


## Receptor distances
```{r warning=F}
circle_distances <- c(seq(6, 50, 2),
                      seq(55, 110, 5),
                      seq(120, 200, 10),
                      seq(220, 400, 20),
                      seq(450, 700, 50),
                      seq(800, 1100, 100),
                      1300, 1600, 2000, 2500, 3000)
                      
cat(circle_distances)
```

## Generate receptor coordinates with `receptors` package
```{r warning=F, fig.width = 7.2, fig.height = 6.4}
library(receptors)
recept_grid <- rings_grid(center_x  = 0, 
                          center_y  = 0, 
                          radii     = circle_distances[1:30],
                          spacing   = circle_distances[1:30] / 100 + 1,
                          show_plot = TRUE)
```


## Add elevations
```{r warning=F}
recept_grid$elevation <- 255
```


## Write receptor grid to a `.rou` file
```{r warning=F}
write_rou(data        = recept_grid, 
          path        = "circle_grid.rou",
          grid_type   = "disccart",
          elev_units  = "meters")
```
